### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by Malizma333** [LunaKampling/LROverhaul#12]
After the new UI update, it might be good to implement a style guide before adding any other features, as sooner is better than later. This would keep coding practices consistent throughout the solution and between developers.

To enforce a coding style, a .editorconfig file can be generated by going to `Tools -> Options -> Text Editor -> C# -> Code Style`, adjusting the appropriate preferences, then pressing `Generate .editorconfig file from settings` and saving it in the solution directory. Changes based on the .editorconfig file can be applied by right-clicking the solution and going to `Analyze and Code Cleanup -> Run Code Cleanup (Profile 1)`. This action will apply all code style preferences to the entire solution but may take some time to complete (my machine took about 10-15 minutes to run through the entire solution, but it might vary based on style preferences).

More information about coding styles/setup can be found [here](https://learn.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2022). Recommended coding conventions can be found [here](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions) to get started with code styling preferences.

**Comment by OddMorning** [comment]
I planned to do a code cleanup and stuff after finishing the rest of the UI update (it's mostly about scalable UI). Didn't do it earlier because it'd make hard to compare LRO with my fork.

Gonna leave it up to Luna
